### ISSUE TITLE
When displaying the vehicle details, it always shows air pressure 28. And it throws an exception when entering the tire pressure of a truck

### ISSUE THREAD

**Issue by bjd54321** [bjd54321/Ex03#10]

**Comment by Aleosha** [comment]
Fixed

01.01.2015, 10:35, "bjd54321" notifications@github.com:

**Comment by bjd54321** [comment]
It still shows air pressure 28 no matter what the air pressure is...
